services:
  backend:
    build: ./backend
    container_name: complex-forms-backend
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=development
      - PORT=3100
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
